class DataInstance():

    def __init__(self, data: dict) -> None:
        self.problem_size = data["problem_size"]
        self.seed = data["seed"]
        self.I = data["I"]
        self.J = data["J"]
        self.K = data["K"]
        self.T = data["T"]
        self.best = data["best"]
        self.treat = data["treat"]
        self.qualified = data["qualified"]
        self.doctor_rank = data["doctor_rank"]
        self.doctor_available = data["doctor_available"]
        self.patient_diseases = data["patient_diseases"]
        self.allocate_rank = data["allocate_rank"]
        self.patient_available = data["patient_available"]
        self.patient_time_prefs = data["patient_time_prefs"]
        self.doctor_times = data["doctor_times"]
        self.patient_times = data["patient_times"]
        self.START = data["START"]
        self.DURATION = data["DURATION"]
        self.I_k = data["I_k"]
        self.J_k = data["J_k"]
        self.diseases_doctor_qualified_for = data["diseases_doctor_qualified_for"]
        self.compatible_times = data["compatible_times"]
        self.patients_doctor_can_treat = data["patients_doctor_can_treat"]
        self.numberAvailableDoctors = data["numberAvailableDoctors"]
        self.patientDoctorScore = data["patientDoctorScore"]
        self.patientTimeScore = data["patientTimeScore"]
        self.doctor_num_diseases_can_treat = data["doctor_num_diseases_can_treat"]
        self.doctor_disease_rank_scores = data["doctor_disease_rank_scores"]
        self.M1 = data["M1"]